In [1]:
import numpy as np

In [2]:
rewards = np.load('rewards.npy', allow_pickle=True)

In [3]:
print(rewards.shape)

(125, 5)


In [4]:
print(rewards)

[[-0.38701486 -1.04230522 -0.71616449 -0.62627198 -0.08948945]
 [-1.02249626 -0.96130251 -1.51475838  0.10314932  0.01267886]
 [-0.62713805 -0.77115095 -1.62617489  0.49466502  0.03510471]
 [-0.25738028 -0.91656599 -1.37232644  0.85311875 -0.01877306]
 [-0.26077892 -0.07989847 -1.83778137  0.43241836 -0.36296232]
 [-0.34388745 -0.53239462 -1.6743865   0.87733915 -0.375657  ]
 [-0.30756428 -0.83744323 -2.4375085   1.40125551  0.09748342]
 [-0.28838094 -0.48889177 -2.5287226   1.15651521  0.28938942]
 [-0.2866656  -0.42110028 -1.80590546  1.57978586 -0.06165388]
 [-0.22130987 -0.70140388 -1.98632326  1.05387255  1.71358327]
 [-0.03097654 -0.26963553 -2.01997704  1.15493214  1.44636562]
 [-0.37518766 -0.51415335 -2.5153892   1.5739048   2.18178489]
 [-0.21831533 -0.22234589 -2.08818108  1.55703867  2.00225196]
 [-0.39547082 -0.21803896 -2.46511701  1.70094003  2.0104641 ]
 [-0.41220045 -0.53845139 -2.56601155  1.30039405  1.57672206]
 [-0.4648396  -0.46742345 -2.20752875  1.41118909  2.42

In [6]:
succeded = np.load('succeded.npy', allow_pickle=True)

In [7]:
print(succeded)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False Fa