In [2]:
import numpy as np
rewards = np.load('rewards.npy')
print(rewards)

[[ 0.31846985  0.35511122 -0.70082426  0.20498377  0.05319461]
 [ 0.86969595  0.65142143 -0.10902747  0.45498383  1.11854271]
 [ 1.74125682  0.20805891  0.30741652 -0.1069689   1.94646787]
 [ 1.416089    1.5697641  -0.36927334  1.27314548  1.78552676]
 [ 2.38471184  1.82563657 -0.41275183  1.40824142  1.85005726]
 [ 2.60062912  2.36180252  1.60481919  2.08404233  1.85993084]
 [ 2.03469415  2.03152528  2.34539981  2.56316122  2.5879959 ]
 [ 2.95662282  2.99851188  3.78361553  3.08851495  2.45014095]
 [ 2.92472406  2.80481691  2.50971456  3.31535767  2.49581419]
 [ 3.37588134  2.74813906  3.02981862  2.90693273  2.6919024 ]
 [ 2.6847737   2.89938388  2.99410426  2.74034601  2.60925262]
 [ 4.12904454  3.03135101  3.44130255  3.59136658  2.98223034]
 [ 3.63091844  3.4883573   3.8655933   3.15416898  2.87514944]
 [ 3.39511264  3.62342231  4.15732417  3.3252617   3.63589537]
 [ 4.40269555  4.00931089  3.12373103  3.47915896  3.79774061]
 [ 4.54605071  3.78173592  4.03509721  3.92930435  3.81