In [1]:
import numpy as np
rewards = np.load('rewards.npy', allow_pickle=True)
succeded = np.load('succeded.npy', allow_pickle=True)

In [2]:
print(rewards)

[[-1.19815146 -0.76304675 -0.77803225 -0.61262107 -0.29118318]
 [-1.15907495 -0.29956978 -0.63122645 -1.29707977 -0.34462087]
 [-0.23506634 -0.0351963  -0.25587189 -1.13694551  0.12397581]
 [-0.43200472 -0.54792455 -0.4625857  -1.00086224 -0.35245433]
 [-0.17368614 -0.16471745 -0.53705464 -1.80278821 -0.61101545]
 [-0.34064888 -0.47021194 -0.53582455 -1.62412977  0.12030782]
 [-0.52461848 -0.36346872 -0.27134456 -1.45944999  0.03595709]
 [-0.49200382 -0.17217692 -0.42403795 -2.1097607   1.29181485]
 [-0.77345672 -0.0704976  -0.03415593  0.12112463  1.72738284]
 [-0.45834101 -0.40383421  0.19367337  0.3378647   1.65139622]
 [-0.43401456 -0.83071902 -0.31849773  0.58082678  1.60463068]
 [-0.65442313 -0.74519619 -0.35483606  0.40588979  1.49976216]
 [-0.02581545 -0.23112189 -0.26693857  0.1688557   1.74026063]
 [-0.3962058  -0.13068594 -0.13750554  0.58050051  2.08954242]
 [-0.76511812 -0.13211619 -0.07102028  0.11786016  1.73948711]
 [-0.56879555 -0.71394262  1.64495683  0.2504799   2.44