In [1]:
import numpy as np
rewards = np.load('rewards.npy')
print(rewards)

[[-0.08468183 -0.08217994 -0.10268097 -0.39008769  0.24529902]
 [-0.19831894  0.50877196  0.04183939  0.62996456  1.16450975]
 [ 1.02704588  0.62754238  1.62562713 -0.3223682   1.46487911]
 [ 1.53565084  1.54525693  1.18044508  1.03325212  1.77918903]
 [ 2.90996919  2.06437747  2.47280224  1.38003523  2.31277435]
 [ 2.93752935  2.28708889  2.65204167  1.87622173  2.31812571]
 [ 2.72447951  2.04004979  2.70170597  2.3011796   2.40207874]
 [ 2.47212333  2.71496315  2.42847529  2.73942723  2.08001834]
 [ 2.76842556  2.59613766  2.53375979  2.72140609  2.5183585 ]
 [ 3.23376658  2.51402452  3.05068649  3.43969581  2.61211906]
 [ 2.97813845  2.94453331  2.30521986  3.76886903  2.97513329]
 [ 4.55806283  2.85070158  3.37341851  3.70073444  2.78350728]
 [ 4.08881219  3.15217854  3.61645768  2.65051489  3.41122243]
 [ 4.17262114  3.09999899  4.11201406  3.13045745  4.07650012]
 [ 3.80010701  3.38916046  3.24879414  3.51763362  3.17953967]
 [ 4.35393406  3.60771117  3.8415484   3.64374956  3.80

In [ ]:
~